[2023-07-12 19:30:00,468: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 19:30:00,468: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 19:31:00,409: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 19:31:00,409: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 19:31:01,796: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 19:31:01,815: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 19:31:01,818: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 19:31:01,819: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\common\utils.py", line 21, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 9, in <module>
    data_ingestion.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 11, in main
    config=ConfigurationManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\config\configuration_manager.py", line 11, in __init__
    self.params=read_yaml(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\common\utils.py", line 23, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2023-07-12 19:31:18,045: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 19:31:18,045: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 19:31:19,461: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 19:31:19,475: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 19:31:19,483: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 19:31:19,483: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\common\utils.py", line 21, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 9, in <module>
    data_ingestion.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 11, in main
    config=ConfigurationManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\config\configuration_manager.py", line 11, in __init__
    self.params=read_yaml(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\common\utils.py", line 23, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2023-07-12 19:32:04,445: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 19:32:04,460: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 19:32:05,832: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 19:32:05,839: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 19:32:05,849: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 19:32:05,866: INFO: data_ingestion: Input data file loaded.]
[2023-07-12 19:32:05,870: INFO: utils: created directory at: artifacts/data/transformed_data]
[2023-07-12 19:32:05,881: INFO: data_ingestion: Train and test data created.]
[2023-07-12 19:32:05,882: ERROR: data_ingestion: 'DataIngestion' object has no attribute 'data_ingestion_config']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_ingestion.py", line 27, in ingest_data
    return (self.data_ingestion_config.train_data_path, self.data_ingestion_config.test_data_path)
AttributeError: 'DataIngestion' object has no attribute 'data_ingestion_config'
[2023-07-12 19:32:05,884: ERROR: main: 'DataIngestion' object has no attribute 'data_ingestion_config']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 9, in <module>
    data_ingestion.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 13, in main
    data_ingestion.ingest_data()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_ingestion.py", line 31, in ingest_data
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_ingestion.py", line 27, in ingest_data
    return (self.data_ingestion_config.train_data_path, self.data_ingestion_config.test_data_path)
AttributeError: 'DataIngestion' object has no attribute 'data_ingestion_config'
[2023-07-12 19:32:59,440: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 19:32:59,440: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 19:33:00,845: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 19:33:00,858: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 19:33:00,859: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 19:33:00,869: INFO: data_ingestion: Input data file loaded.]
[2023-07-12 19:33:00,881: INFO: data_ingestion: Train and test data created.]
[2023-07-12 19:33:00,882: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:12:57,792: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:12:57,792: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:12:59,885: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:12:59,892: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:12:59,895: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:12:59,918: INFO: data_ingestion: Input data file loaded.]
[2023-07-12 20:12:59,919: INFO: data_ingestion: Data already exists. Skipping ingestion.]
[2023-07-12 20:12:59,920: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:24:36,453: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:24:36,453: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:24:37,871: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:24:37,886: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:24:37,888: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:24:37,896: INFO: data_ingestion: Input data file loaded.]
[2023-07-12 20:24:37,915: INFO: data_ingestion: Train and test data created.]
[2023-07-12 20:24:37,916: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:24:56,327: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:24:56,327: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:24:57,691: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:24:57,702: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:24:57,704: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:24:57,705: INFO: data_ingestion: Data already exists. Skipping ingestion.]
[2023-07-12 20:24:57,706: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:38:48,039: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:38:48,039: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:38:49,645: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:38:49,662: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:38:49,663: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:38:49,664: INFO: data_ingestion: Data already exists. Skipping ingestion.]
[2023-07-12 20:38:49,664: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:38:49,665: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-12 20:38:49,667: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:38:49,667: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:38:49,699: ERROR: data_transformer: 'DataConfig' object has no attribute 'target_column']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_transformer.py", line 57, in transform_data
    target_column=self.config.target_column
AttributeError: 'DataConfig' object has no attribute 'target_column'
[2023-07-12 20:38:49,701: ERROR: main: 'DataConfig' object has no attribute 'target_column']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 22, in <module>
    data_tranformer.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s2_data_transformation_pipeline.py", line 13, in main
    data_transformer.transform_data()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_transformer.py", line 78, in transform_data
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_transformer.py", line 57, in transform_data
    target_column=self.config.target_column
AttributeError: 'DataConfig' object has no attribute 'target_column'
[2023-07-12 20:39:20,705: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:39:20,705: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:39:22,139: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:39:22,155: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:39:22,157: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:39:22,157: INFO: data_ingestion: Data already exists. Skipping ingestion.]
[2023-07-12 20:39:22,157: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:39:22,159: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-12 20:39:22,162: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:39:22,163: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:39:22,218: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-12 20:47:21,102: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:47:21,102: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:47:22,712: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:47:22,724: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:47:22,735: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:47:22,736: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-12 20:47:22,739: ERROR: data_ingestion: [WinError 267] The directory name is invalid: 'artifacts/data/original_data/train_data.csv']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_ingestion.py", line 39, in ingest_data
    remove_directories([self.config.data_train_path, self.config.data_test_path])
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\common\utils.py", line 41, in remove_directories
    shutil.rmtree(path)
  File "C:\Users\fhash\anaconda3\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\fhash\anaconda3\lib\shutil.py", line 601, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\fhash\anaconda3\lib\shutil.py", line 598, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts/data/original_data/train_data.csv'
[2023-07-12 20:47:22,744: ERROR: main: [WinError 267] The directory name is invalid: 'artifacts/data/original_data/train_data.csv']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 11, in <module>
    data_ingestion.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 13, in main
    data_ingestion.ingest_data()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_ingestion.py", line 46, in ingest_data
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data_ingestion.py", line 39, in ingest_data
    remove_directories([self.config.data_train_path, self.config.data_test_path])
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\common\utils.py", line 41, in remove_directories
    shutil.rmtree(path)
  File "C:\Users\fhash\anaconda3\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\fhash\anaconda3\lib\shutil.py", line 601, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\fhash\anaconda3\lib\shutil.py", line 598, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts/data/original_data/train_data.csv'
[2023-07-12 20:50:23,943: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:50:23,943: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:50:25,743: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:50:25,757: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:50:25,759: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:50:25,760: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-12 20:50:25,761: INFO: utils: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-12 20:50:25,763: INFO: utils: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-12 20:50:25,778: INFO: data_ingestion: Input data file loaded.]
[2023-07-12 20:50:25,789: INFO: data_ingestion: Train and test data created.]
[2023-07-12 20:50:25,790: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:50:25,790: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-12 20:50:25,795: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:50:25,797: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:50:25,847: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-12 20:57:06,294: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-12 20:57:06,294: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-12 20:57:07,974: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-12 20:57:07,977: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:57:07,977: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:57:07,983: INFO: data_ingestion: Input data file loaded.]
[2023-07-12 20:57:07,989: INFO: data_ingestion: Train and test data created.]
[2023-07-12 20:57:07,989: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-12 20:57:07,989: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-12 20:57:07,991: INFO: utils: yaml file: configuration\config.yaml loaded successfully]
[2023-07-12 20:57:07,992: INFO: utils: yaml file: configuration\params.yaml loaded successfully]
[2023-07-12 20:57:08,048: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-17 18:34:53,628: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 18:34:53,628: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 18:36:05,399: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 18:36:05,399: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 18:36:07,290: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 18:36:07,290: INFO: common: yaml file: configuration\config.yaml loaded successfully]
[2023-07-17 18:36:07,290: INFO: common: yaml file: configuration\params.yaml loaded successfully]
[2023-07-17 18:36:07,290: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-17 18:36:07,290: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-17 18:36:07,290: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-17 18:36:07,318: INFO: data_ingestion: Input data file loaded.]
[2023-07-17 18:36:07,328: INFO: data_ingestion: Train and test data created.]
[2023-07-17 18:36:07,328: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-17 18:36:07,330: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-17 18:36:07,332: INFO: common: yaml file: configuration\config.yaml loaded successfully]
[2023-07-17 18:36:07,334: INFO: common: yaml file: configuration\params.yaml loaded successfully]
[2023-07-17 18:36:07,390: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-17 18:41:54,074: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 18:41:54,074: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 18:41:55,768: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 18:41:55,771: INFO: common: yaml file: configuration\config.yaml loaded successfully]
[2023-07-17 18:41:55,772: INFO: common: yaml file: configuration\params.yaml loaded successfully]
[2023-07-17 18:41:55,773: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-17 18:41:55,774: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-17 18:41:55,775: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-17 18:41:55,784: INFO: data_ingestion: Input data file loaded.]
[2023-07-17 18:41:55,795: INFO: data_ingestion: Train and test data created.]
[2023-07-17 18:41:55,796: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-17 18:41:55,797: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-17 18:41:55,800: INFO: common: yaml file: configuration\config.yaml loaded successfully]
[2023-07-17 18:41:55,804: INFO: common: yaml file: configuration\params.yaml loaded successfully]
[2023-07-17 18:41:55,881: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-17 18:46:47,296: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 18:46:47,296: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 18:46:59,833: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 18:46:59,833: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 18:47:01,272: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 18:47:01,272: ERROR: main: [Errno 2] No such file or directory: 'configuration\\config.yaml']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 11, in <module>
    data_ingestion.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 11, in main
    config=ConfigurationManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 10, in __init__
    self.config=read_yaml(config_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 25, in read_yaml
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 18, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'configuration\\config.yaml'
[2023-07-17 18:47:21,099: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 18:47:21,099: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 18:47:22,509: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 18:47:22,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 18:47:22,521: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-17 18:47:22,521: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-17 18:47:22,521: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-17 18:47:22,521: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-17 18:47:22,531: INFO: data_ingestion: Input data file loaded.]
[2023-07-17 18:47:22,540: INFO: data_ingestion: Train and test data created.]
[2023-07-17 18:47:22,541: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-17 18:47:22,543: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-17 18:47:22,546: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 18:47:22,547: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-17 18:47:22,599: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-17 20:30:19,665: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 20:30:19,665: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 20:31:27,111: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 20:31:27,111: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 20:31:28,574: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 20:31:28,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 20:31:28,594: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-17 20:31:28,595: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-17 20:31:28,596: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-17 20:31:28,604: INFO: data_ingestion: Input data file loaded.]
[2023-07-17 20:31:28,615: INFO: data_ingestion: Train and test data created.]
[2023-07-17 20:31:28,616: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-17 20:31:28,617: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-17 20:31:28,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 20:31:28,673: ERROR: data_transformer: 'DataConfig' object has no attribute 'data_transformed_train_array_path']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data\data_transformer.py", line 73, in transform_data
    np.save(self.config.data_transformed_train_array_path, np.c_[X_train_arr, np.array(y_train)])
AttributeError: 'DataConfig' object has no attribute 'data_transformed_train_array_path'
[2023-07-17 20:31:28,675: ERROR: main: 'DataConfig' object has no attribute 'data_transformed_train_array_path']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 22, in <module>
    data_tranformer.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s2_data_transformation_pipeline.py", line 13, in main
    data_transformer.transform_data()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data\data_transformer.py", line 78, in transform_data
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data\data_transformer.py", line 73, in transform_data
    np.save(self.config.data_transformed_train_array_path, np.c_[X_train_arr, np.array(y_train)])
AttributeError: 'DataConfig' object has no attribute 'data_transformed_train_array_path'
[2023-07-17 20:34:05,532: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 20:34:05,532: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 20:34:06,976: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 20:34:06,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 20:34:06,984: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-17 20:34:06,985: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-17 20:34:06,987: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-17 20:34:06,995: INFO: data_ingestion: Input data file loaded.]
[2023-07-17 20:34:07,003: INFO: data_ingestion: Train and test data created.]
[2023-07-17 20:34:07,004: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-17 20:34:07,006: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-17 20:34:07,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 20:34:07,069: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-17 20:35:09,503: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-17 20:35:09,503: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-17 20:35:10,907: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-17 20:35:10,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 20:35:10,907: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-17 20:35:10,907: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-17 20:35:10,923: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-17 20:35:10,923: INFO: data_ingestion: Input data file loaded.]
[2023-07-17 20:35:10,923: INFO: data_ingestion: Train and test data created.]
[2023-07-17 20:35:10,923: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-17 20:35:10,923: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-17 20:35:10,923: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-17 20:35:10,991: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:18:09,262: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:18:09,262: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:18:11,415: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:18:11,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:18:11,419: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:18:11,419: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:18:11,419: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:18:11,430: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:18:11,437: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:18:11,437: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:18:11,438: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:18:11,439: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:18:11,502: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:19:12,974: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:19:12,974: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:20:56,368: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:20:56,368: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:20:58,076: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:20:58,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:20:58,096: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:20:58,098: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:20:58,099: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:20:58,111: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:20:58,122: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:20:58,123: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:20:58,124: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:20:58,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:20:58,180: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:20:58,180: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:20:58,188: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:20:58,204: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:20:58,257: ERROR: model_trainer: "'LinearRegression'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'LinearRegression'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 32, in train_models
    param=self.params[list(self.models.keys())[i]]
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'LinearRegression'"
[2023-07-20 20:20:58,259: ERROR: main: "'LinearRegression'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'LinearRegression'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 64, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 32, in train_models
    param=self.params[list(self.models.keys())[i]]
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'LinearRegression'"
[2023-07-20 20:22:13,179: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:22:13,179: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:22:15,257: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:22:15,264: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:22:15,265: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:22:15,266: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:22:15,268: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:22:15,280: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:22:15,292: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:22:15,292: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:22:15,293: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:22:15,298: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:22:15,378: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:22:15,379: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:22:15,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:22:15,395: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:24:32,943: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:24:32,943: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:24:34,575: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:24:34,578: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:24:34,580: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:24:34,581: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:24:34,582: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:24:34,592: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:24:34,601: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:24:34,602: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:24:34,603: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:24:34,605: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:24:34,655: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:24:34,657: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:24:34,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:24:34,664: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:24:34,690: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:24:34,698: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:25:06,894: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:25:06,895: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:25:08,530: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:25:08,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:25:08,533: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:25:08,535: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:25:08,536: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:25:08,545: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:25:08,555: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:25:08,556: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:25:08,557: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:25:08,559: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:25:08,608: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:25:08,609: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:25:08,612: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:25:08,616: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:25:08,648: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:25:08,652: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:26:09,502: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:26:09,502: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:26:11,593: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:26:11,616: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:26:11,617: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:26:11,618: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:26:11,619: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:26:11,631: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:26:11,644: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:26:11,645: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:26:11,646: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:26:11,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:26:11,713: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:26:11,713: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:26:11,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:26:11,745: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:26:33,827: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:26:33,829: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:28:21,353: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:28:21,353: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:28:22,947: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:28:22,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:28:22,947: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:28:22,947: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:28:22,947: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:28:22,963: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:28:22,963: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:28:22,963: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:28:22,963: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:28:22,973: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:28:23,022: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:28:23,023: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:28:23,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:28:23,030: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:28:23,057: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:28:23,061: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:29:20,264: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:29:20,264: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:29:22,326: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:29:22,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:29:22,336: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:29:22,337: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:29:22,338: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:29:22,349: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:29:22,362: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:29:22,363: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:29:22,364: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:29:22,370: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:29:22,440: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:29:22,440: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:29:22,445: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:29:22,459: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:29:47,243: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:29:47,247: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:30:24,204: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:30:24,204: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:30:25,811: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:30:25,826: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:25,827: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:30:25,828: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:30:25,829: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:30:25,840: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:30:25,851: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:30:25,852: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:30:25,853: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:30:25,855: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:25,906: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:30:25,906: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:30:25,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:25,915: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:30:25,916: ERROR: main: Return value of <function read_yaml at 0x0000018DCE9EC700> of type <class 'dict'> does not match annotation type <class 'box.config_box.ConfigBox'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer=ModelBuilder(data_config=config.get_data_config(), model_config=config.get_model_config())
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml at 0x0000018DCE9EC700> of type <class 'dict'> does not match annotation type <class 'box.config_box.ConfigBox'>
[2023-07-20 20:30:52,436: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:30:52,436: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:30:54,498: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:30:54,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:54,504: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:30:54,505: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:30:54,505: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:30:54,517: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:30:54,530: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:30:54,531: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:30:54,533: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:30:54,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:54,597: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:30:54,597: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:30:54,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:54,623: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:30:54,624: ERROR: main: Return value of <function read_yaml at 0x0000019F757C43A0> of type <class 'dict'> does not match annotation type <class 'box.config_box.ConfigBox'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer=ModelBuilder(data_config=config.get_data_config(), model_config=config.get_model_config())
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml at 0x0000019F757C43A0> of type <class 'dict'> does not match annotation type <class 'box.config_box.ConfigBox'>
[2023-07-20 20:31:28,515: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:31:28,515: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:31:30,110: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:31:30,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:31:30,127: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:31:30,128: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:31:30,130: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:31:30,139: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:31:30,149: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:31:30,150: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:31:30,151: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:31:30,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:31:30,201: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:31:30,202: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:31:30,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:31:30,209: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:31:30,242: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:31:30,247: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:32:04,726: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:32:04,726: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:32:06,827: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:32:06,843: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:32:06,844: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:32:06,844: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:32:06,845: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:32:06,858: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:32:06,870: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:32:06,871: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:32:06,872: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:32:06,877: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:32:06,937: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:32:06,937: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:32:06,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:32:06,962: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:32:45,267: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:32:45,271: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:33:31,365: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:33:31,365: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:33:33,419: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:33:33,432: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:33:33,433: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:33:33,434: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:33:33,435: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:33:33,449: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:33:33,461: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:33:33,462: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:33:33,463: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:33:33,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:33:33,526: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:33:33,526: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:33:33,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:33:33,556: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:35:27,198: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:35:27,198: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:35:29,317: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:35:29,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:35:29,328: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:35:29,329: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:35:29,329: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:35:29,341: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:35:29,354: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:35:29,355: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:35:29,356: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:35:29,360: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:35:29,423: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:35:29,423: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:35:29,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:35:29,444: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:36:04,945: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:36:04,957: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:37:07,049: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:37:07,049: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:37:08,840: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:37:08,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:37:08,846: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:37:08,846: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:37:08,846: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:37:08,858: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:37:08,868: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:37:08,869: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:37:08,870: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:37:08,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:37:08,919: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:37:08,920: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:37:08,922: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:37:08,927: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:37:08,957: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:37:08,961: ERROR: main: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:37:51,490: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:37:51,490: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:37:53,577: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:37:53,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:37:53,599: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:37:53,600: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:37:53,600: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:37:53,615: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:37:53,626: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:37:53,627: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:37:53,628: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:37:53,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:37:53,694: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:37:53,694: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:37:53,708: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:37:53,723: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:38:55,715: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:38:55,715: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:38:58,503: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:38:58,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:38:58,512: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:38:58,513: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:38:58,514: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:38:58,525: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:38:58,536: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:38:58,536: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:38:58,537: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:38:58,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:39:38,575: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:39:38,576: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:39:38,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:39:38,605: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:40:24,535: ERROR: model_trainer: Found input variables with inconsistent numbers of samples: [800, 200]]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 38, in train_models
    gsv.fit(self.X_train,self.y_train)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\model_selection\_search.py", line 782, in fit
    X, y, groups = indexable(X, y, groups)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 443, in indexable
    check_consistent_length(*result)
  File "C:\Users\fhash\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 397, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [800, 200]
[2023-07-20 20:41:53,610: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:41:53,610: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:41:55,681: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:41:55,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:41:55,694: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:41:55,695: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:41:55,696: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:41:55,708: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:41:55,719: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:41:55,721: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:41:55,722: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:41:55,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:43:45,946: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:43:45,946: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:43:47,599: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:43:47,599: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:43:47,611: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:43:47,611: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:43:47,611: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:43:47,615: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:43:47,615: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:43:47,615: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:43:47,615: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:43:47,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:43:47,672: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:43:47,673: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:43:47,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:43:47,681: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:44:35,039: INFO: main: >>>>>> Model Training stage completed <<<<<<

x==========x]
[2023-07-20 20:57:38,204: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 20:57:38,204: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 20:57:39,971: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 20:57:39,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:57:39,991: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 20:57:39,992: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 20:57:39,992: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 20:57:40,013: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 20:57:40,021: INFO: data_ingestion: Train and test data created.]
[2023-07-20 20:57:40,022: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 20:57:40,023: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 20:57:40,026: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:57:40,079: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 20:57:40,080: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 20:57:40,082: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:57:40,087: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 20:57:40,131: INFO: model_trainer: Training GSV to find best parameters for LinearRegression]
[2023-07-20 20:57:40,155: INFO: model_trainer: Training LinearRegression on training data]
[2023-07-20 20:57:40,158: INFO: model_trainer: Training GSV to find best parameters for DecisionTreeRegressor]
[2023-07-20 20:57:40,221: INFO: model_trainer: Training DecisionTreeRegressor on training data]
[2023-07-20 20:57:40,241: INFO: model_trainer: Training GSV to find best parameters for RandomForestRegressor]
[2023-07-20 20:57:43,405: INFO: model_trainer: Training RandomForestRegressor on training data]
[2023-07-20 20:57:43,986: INFO: model_trainer: Training GSV to find best parameters for AdaBoostRegressor]
[2023-07-20 20:57:50,140: INFO: model_trainer: Training AdaBoostRegressor on training data]
[2023-07-20 20:57:50,204: INFO: model_trainer: Training GSV to find best parameters for GradientBoostRegressor]
[2023-07-20 20:58:09,905: INFO: model_trainer: Training GradientBoostRegressor on training data]
[2023-07-20 20:58:10,009: INFO: model_trainer: Training GSV to find best parameters for XGBRegressor]
[2023-07-20 20:58:13,597: INFO: model_trainer: Training XGBRegressor on training data]
[2023-07-20 20:58:13,677: INFO: model_trainer: Training GSV to find best parameters for CatBoostRegressor]
[2023-07-20 20:58:27,111: INFO: model_trainer: Training CatBoostRegressor on training data]
[2023-07-20 20:58:27,280: INFO: model_trainer: Saving Results to json file]
[2023-07-20 20:58:27,280: INFO: common: json file saved at: scores.json]
[2023-07-20 20:58:27,295: INFO: model_trainer: LinearRegression is the model with r2_score as 0.8804311859808921]
[2023-07-20 20:58:27,302: INFO: main: >>>>>> Model Training stage completed <<<<<<

x==========x]
[2023-07-20 21:16:18,701: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 21:16:18,701: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 21:16:20,479: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 21:16:20,483: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:16:20,484: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 21:16:20,486: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 21:16:20,488: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 21:16:20,497: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 21:16:20,505: INFO: data_ingestion: Train and test data created.]
[2023-07-20 21:16:20,506: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 21:16:20,507: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 21:16:20,509: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:16:20,559: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 21:16:20,560: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 21:16:20,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:16:20,567: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 21:16:20,595: INFO: model_trainer: Training GSV to find best parameters for LinearRegression]
[2023-07-20 21:16:20,617: INFO: model_trainer: Training LinearRegression on training data]
[2023-07-20 21:16:20,621: INFO: model_trainer: Evaluating LinearRegression with r2_score: 0.8804311859808921]
[2023-07-20 21:16:20,622: INFO: model_trainer: Training GSV to find best parameters for DecisionTreeRegressor]
[2023-07-20 21:16:20,691: INFO: model_trainer: Training DecisionTreeRegressor on training data]
[2023-07-20 21:16:20,708: INFO: model_trainer: Evaluating DecisionTreeRegressor with r2_score: 0.7649569488416131]
[2023-07-20 21:16:20,709: INFO: model_trainer: Training GSV to find best parameters for RandomForestRegressor]
[2023-07-20 21:16:23,967: INFO: model_trainer: Training RandomForestRegressor on training data]
[2023-07-20 21:16:24,539: INFO: model_trainer: Evaluating RandomForestRegressor with r2_score: 0.8536562965727417]
[2023-07-20 21:16:24,539: INFO: model_trainer: Training GSV to find best parameters for AdaBoostRegressor]
[2023-07-20 21:16:30,765: INFO: model_trainer: Training AdaBoostRegressor on training data]
[2023-07-20 21:16:30,920: INFO: model_trainer: Evaluating AdaBoostRegressor with r2_score: 0.8513279858819309]
[2023-07-20 21:16:30,920: INFO: model_trainer: Training GSV to find best parameters for GradientBoostRegressor]
[2023-07-20 21:17:13,830: INFO: model_trainer: Training GradientBoostRegressor on training data]
[2023-07-20 21:17:14,158: INFO: model_trainer: Evaluating GradientBoostRegressor with r2_score: 0.874844864558493]
[2023-07-20 21:17:14,158: INFO: model_trainer: Training GSV to find best parameters for XGBRegressor]
[2023-07-20 21:17:18,767: INFO: model_trainer: Training XGBRegressor on training data]
[2023-07-20 21:17:18,895: INFO: model_trainer: Evaluating XGBRegressor with r2_score: 0.8628772402712002]
[2023-07-20 21:17:18,895: INFO: model_trainer: Training GSV to find best parameters for CatBoostRegressor]
[2023-07-20 21:17:34,022: INFO: model_trainer: Training CatBoostRegressor on training data]
[2023-07-20 21:17:34,191: INFO: model_trainer: Evaluating CatBoostRegressor with r2_score: 0.8566301224032382]
[2023-07-20 21:17:34,191: INFO: model_trainer: Saving Results to json file]
[2023-07-20 21:17:34,191: INFO: common: json file saved at: scores.json]
[2023-07-20 21:17:34,191: INFO: model_trainer: LinearRegression is the best model with r2_score as 0.8804311859808921]
[2023-07-20 21:17:34,206: INFO: main: >>>>>> Model Training stage completed <<<<<<

x==========x]
[2023-07-20 21:18:13,879: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 21:18:13,879: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 21:18:15,960: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 21:18:15,964: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:18:15,965: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 21:18:15,966: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 21:18:15,967: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 21:18:15,980: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 21:18:15,990: INFO: data_ingestion: Train and test data created.]
[2023-07-20 21:18:15,991: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 21:18:15,992: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 21:18:15,994: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:18:16,050: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 21:18:16,051: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 21:18:16,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:18:16,060: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 21:18:16,093: INFO: model_trainer: Training GSV to find best parameters for LinearRegression]
[2023-07-20 21:18:16,122: INFO: model_trainer: Training LinearRegression on training data]
[2023-07-20 21:18:16,125: INFO: model_trainer: Evaluating LinearRegression with r2_scores: failed]
[2023-07-20 21:18:16,126: INFO: model_trainer: Training GSV to find best parameters for DecisionTreeRegressor]
[2023-07-20 21:18:16,195: INFO: model_trainer: Training DecisionTreeRegressor on training data]
[2023-07-20 21:18:16,215: INFO: model_trainer: Evaluating DecisionTreeRegressor with r2_scores: failed]
[2023-07-20 21:18:16,216: INFO: model_trainer: Training GSV to find best parameters for RandomForestRegressor]
[2023-07-20 21:18:19,692: INFO: model_trainer: Training RandomForestRegressor on training data]
[2023-07-20 21:18:20,360: INFO: model_trainer: Evaluating RandomForestRegressor with r2_scores: failed]
[2023-07-20 21:18:20,360: INFO: model_trainer: Training GSV to find best parameters for AdaBoostRegressor]
[2023-07-20 21:18:27,196: INFO: model_trainer: Training AdaBoostRegressor on training data]
[2023-07-20 21:18:27,381: INFO: model_trainer: Evaluating AdaBoostRegressor with r2_scores: failed]
[2023-07-20 21:18:27,381: INFO: model_trainer: Training GSV to find best parameters for GradientBoostRegressor]
[2023-07-20 21:18:48,447: INFO: model_trainer: Training GradientBoostRegressor on training data]
[2023-07-20 21:18:48,587: INFO: model_trainer: Evaluating GradientBoostRegressor with r2_scores: failed]
[2023-07-20 21:18:48,588: INFO: model_trainer: Training GSV to find best parameters for XGBRegressor]
[2023-07-20 21:18:52,244: INFO: model_trainer: Training XGBRegressor on training data]
[2023-07-20 21:18:52,336: INFO: model_trainer: Evaluating XGBRegressor with r2_scores: failed]
[2023-07-20 21:18:52,336: INFO: model_trainer: Training GSV to find best parameters for CatBoostRegressor]
[2023-07-20 21:19:06,134: INFO: model_trainer: Training CatBoostRegressor on training data]
[2023-07-20 21:19:06,306: INFO: model_trainer: Evaluating CatBoostRegressor with r2_scores: failed]
[2023-07-20 21:19:06,306: INFO: model_trainer: Saving Results to json file]
[2023-07-20 21:19:06,315: INFO: common: json file saved at: scores.json]
[2023-07-20 21:19:06,316: ERROR: model_trainer: '<' not supported between instances of 'str' and 'float']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    if best_model_score<0.6:
TypeError: '<' not supported between instances of 'str' and 'float'
[2023-07-20 21:19:06,318: ERROR: main: '<' not supported between instances of 'str' and 'float']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 76, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 67, in train_models
    if best_model_score<0.6:
TypeError: '<' not supported between instances of 'str' and 'float'
[2023-07-20 21:19:32,479: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 21:19:32,479: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 21:19:34,151: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 21:19:34,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:19:34,153: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 21:19:34,153: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 21:19:34,153: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 21:19:34,165: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 21:19:34,174: INFO: data_ingestion: Train and test data created.]
[2023-07-20 21:19:34,174: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 21:19:34,175: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 21:19:34,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:19:34,227: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 21:19:34,228: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 21:19:34,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:19:34,236: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 21:19:34,267: INFO: model_trainer: Training GSV to find best parameters for LinearRegression]
[2023-07-20 21:19:34,290: INFO: model_trainer: Training LinearRegression on training data]
[2023-07-20 21:19:34,295: ERROR: model_trainer: 'ModelEvaluator' object has no attribute 'r2_scores']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 53, in train_models
    test_model_score = model_evaluator.evaluate()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_evaluator.py", line 12, in evaluate
    return getattr(self, str(self.metric))()
AttributeError: 'ModelEvaluator' object has no attribute 'r2_scores'
[2023-07-20 21:19:34,298: ERROR: main: 'ModelEvaluator' object has no attribute 'r2_scores']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 35, in <module>
    obj.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 14, in main
    model_builder_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 36, in train_models
    model_trainer.train_models()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 76, in train_models
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_trainer.py", line 53, in train_models
    test_model_score = model_evaluator.evaluate()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_evaluator.py", line 12, in evaluate
    return getattr(self, str(self.metric))()
AttributeError: 'ModelEvaluator' object has no attribute 'r2_scores'
[2023-07-20 21:19:52,022: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 21:19:52,037: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 21:19:53,767: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 21:19:53,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:19:53,771: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 21:19:53,772: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 21:19:53,774: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 21:19:53,784: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 21:19:53,797: INFO: data_ingestion: Train and test data created.]
[2023-07-20 21:19:53,798: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 21:19:53,798: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2023-07-20 21:19:53,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:19:53,863: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2023-07-20 21:19:53,864: INFO: main: >>>>>> Model Training stage started <<<<<<]
[2023-07-20 21:19:53,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:19:53,871: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 21:19:53,905: INFO: model_trainer: Training GSV to find best parameters for LinearRegression]
[2023-07-20 21:19:53,927: INFO: model_trainer: Training LinearRegression on training data]
[2023-07-20 21:19:53,933: INFO: model_trainer: Evaluating LinearRegression with r2_score: 0.8804311859808921]
[2023-07-20 21:19:53,934: INFO: model_trainer: Training GSV to find best parameters for DecisionTreeRegressor]
[2023-07-20 21:19:54,001: INFO: model_trainer: Training DecisionTreeRegressor on training data]
[2023-07-20 21:19:54,019: INFO: model_trainer: Evaluating DecisionTreeRegressor with r2_score: 0.7566762993428082]
[2023-07-20 21:19:54,020: INFO: model_trainer: Training GSV to find best parameters for RandomForestRegressor]
[2023-07-20 21:19:57,281: INFO: model_trainer: Training RandomForestRegressor on training data]
[2023-07-20 21:19:57,599: INFO: model_trainer: Evaluating RandomForestRegressor with r2_score: 0.8529865395834958]
[2023-07-20 21:19:57,599: INFO: model_trainer: Training GSV to find best parameters for AdaBoostRegressor]
[2023-07-20 21:47:22,975: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 21:47:22,975: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 21:47:24,618: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-07-20 21:47:24,618: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:47:24,618: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 21:47:24,618: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 21:47:24,618: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 21:47:24,618: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 21:47:24,636: INFO: data_ingestion: Train and test data created.]
[2023-07-20 21:47:24,637: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-07-20 21:47:24,638: INFO: main: >>>>>> stage %S started <<<<<<]
[2023-07-20 21:47:24,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:47:24,690: INFO: main: >>>>>> stage %S completed <<<<<<

x==========x]
[2023-07-20 21:47:24,691: INFO: main: >>>>>> %S started <<<<<<]
[2023-07-20 21:47:24,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:47:24,698: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-20 21:47:24,746: INFO: model_trainer: Training GSV to find best parameters for LinearRegression]
[2023-07-20 21:47:24,769: INFO: model_trainer: Training LinearRegression on training data]
[2023-07-20 21:47:24,773: INFO: model_trainer: Evaluating LinearRegression with r2_score: 0.8804311859808921]
[2023-07-20 21:47:24,774: INFO: model_trainer: Training GSV to find best parameters for DecisionTreeRegressor]
[2023-07-20 21:47:24,839: INFO: model_trainer: Training DecisionTreeRegressor on training data]
[2023-07-20 21:47:24,855: INFO: model_trainer: Evaluating DecisionTreeRegressor with r2_score: 0.744019028644883]
[2023-07-20 21:47:24,856: INFO: model_trainer: Training GSV to find best parameters for RandomForestRegressor]
[2023-07-20 21:47:28,372: INFO: model_trainer: Training RandomForestRegressor on training data]
[2023-07-20 21:47:28,998: INFO: model_trainer: Evaluating RandomForestRegressor with r2_score: 0.8545735267945539]
[2023-07-20 21:47:29,006: INFO: model_trainer: Training GSV to find best parameters for AdaBoostRegressor]
[2023-07-20 21:47:35,900: INFO: model_trainer: Training AdaBoostRegressor on training data]
[2023-07-20 21:47:35,988: INFO: model_trainer: Evaluating AdaBoostRegressor with r2_score: 0.850144769755195]
[2023-07-20 21:47:35,988: INFO: model_trainer: Training GSV to find best parameters for GradientBoostRegressor]
[2023-07-20 21:47:56,177: INFO: model_trainer: Training GradientBoostRegressor on training data]
[2023-07-20 21:47:56,272: INFO: model_trainer: Evaluating GradientBoostRegressor with r2_score: 0.8708359475704899]
[2023-07-20 21:47:56,272: INFO: model_trainer: Training GSV to find best parameters for XGBRegressor]
[2023-07-20 21:47:59,362: INFO: model_trainer: Training XGBRegressor on training data]
[2023-07-20 21:47:59,445: INFO: model_trainer: Evaluating XGBRegressor with r2_score: 0.8628772402712002]
[2023-07-20 21:47:59,446: INFO: model_trainer: Training GSV to find best parameters for CatBoostRegressor]
[2023-07-20 21:48:13,026: INFO: model_trainer: Training CatBoostRegressor on training data]
[2023-07-20 21:48:13,189: INFO: model_trainer: Evaluating CatBoostRegressor with r2_score: 0.8566301224032382]
[2023-07-20 21:48:13,189: INFO: model_trainer: Saving Results to json file]
[2023-07-20 21:48:13,191: INFO: common: json file saved at: scores.json]
[2023-07-20 21:48:13,192: INFO: model_trainer: LinearRegression is the best model with r2_score as 0.8804311859808921]
[2023-07-20 21:48:13,195: INFO: main: >>>>>> %S completed <<<<<<

x==========x]
[2023-07-20 21:50:50,116: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-20 21:50:50,116: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-20 21:50:51,761: INFO: main: Data Ingestion stage started]
[2023-07-20 21:50:51,765: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:50:51,766: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-20 21:50:51,767: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-20 21:50:51,768: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-20 21:50:51,778: INFO: data_ingestion: Input data file loaded.]
[2023-07-20 21:50:51,787: INFO: data_ingestion: Train and test data created.]
[2023-07-20 21:50:51,788: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-20 21:50:51,789: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-20 21:50:51,792: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 21:50:51,845: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-20 21:50:51,846: INFO: main: Model Training stage started]
[2023-07-20 21:50:51,846: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 19:50:36,795: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 19:50:36,795: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 19:50:39,395: INFO: main: Data Ingestion stage started]
[2023-07-21 19:50:39,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:50:39,419: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 19:50:39,419: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 19:50:39,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:50:39,491: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 19:50:39,491: INFO: main: Model Training stage started]
[2023-07-21 19:50:39,491: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 19:54:01,935: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 19:54:01,936: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 19:55:29,377: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 19:55:29,377: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 19:55:30,988: INFO: main: Data Ingestion stage started]
[2023-07-21 19:55:30,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:55:30,999: ERROR: configuration_manager: "'ConfigBox' object has no attribute 'datas'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 19, in get_data_config
    config = self.config.datas
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"
[2023-07-21 19:55:31,021: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 19:55:31,022: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 19:55:31,024: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:55:31,025: ERROR: configuration_manager: "'ConfigBox' object has no attribute 'datas'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 19, in get_data_config
    config = self.config.datas
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"
[2023-07-21 19:55:31,034: ERROR: main: local variable 'data_config' referenced before assignment]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 28, in <module>
    data_tranformer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s2_data_transformer_pipeline.py", line 17, in main
    data_transformer=DataTransformer(config=config.get_data_config())
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 31, in get_data_config
    return data_config
UnboundLocalError: local variable 'data_config' referenced before assignment
[2023-07-21 19:57:23,068: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 19:57:23,068: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 19:57:24,687: INFO: main: Data Ingestion stage started]
[2023-07-21 19:57:24,698: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:57:24,699: ERROR: configuration_manager: Exception occured: "'ConfigBox' object has no attribute 'datas'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 19, in get_data_config
    config = self.config.datas
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"
[2023-07-21 19:57:24,721: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 19:57:24,723: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 19:57:24,726: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:57:24,727: ERROR: configuration_manager: Exception occured: "'ConfigBox' object has no attribute 'datas'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 19, in get_data_config
    config = self.config.datas
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"
[2023-07-21 19:57:24,734: ERROR: main: local variable 'data_config' referenced before assignment]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 28, in <module>
    data_tranformer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s2_data_transformer_pipeline.py", line 17, in main
    data_transformer=DataTransformer(config=config.get_data_config())
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 31, in get_data_config
    return data_config
UnboundLocalError: local variable 'data_config' referenced before assignment
[2023-07-21 19:57:53,317: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 19:57:53,317: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 19:57:54,951: INFO: main: Data Ingestion stage started]
[2023-07-21 19:57:54,956: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:57:54,957: ERROR: configuration_manager: Exception occured: "'ConfigBox' object has no attribute 'datas'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 20, in get_data_config
    config = self.config.datas
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"
[2023-07-21 19:57:54,979: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 19:57:54,980: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 19:57:54,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:57:54,984: ERROR: configuration_manager: Exception occured: "'ConfigBox' object has no attribute 'datas'"]
Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 587, in box.box.Box.__getitem__
KeyError: 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 620, in box.box.Box.__getattr__
  File "box\box.py", line 608, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'datas'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 622, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'datas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 20, in get_data_config
    config = self.config.datas
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 636, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'datas'"
[2023-07-21 19:57:54,990: ERROR: data_transformer: type object 'DataConfig' has no attribute 'data_train_path']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data\data_transformer.py", line 54, in transform_data
    df_train=pd.read_csv(self.config.data_train_path)
AttributeError: type object 'DataConfig' has no attribute 'data_train_path'
[2023-07-21 19:57:54,992: ERROR: main: type object 'DataConfig' has no attribute 'data_train_path']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 28, in <module>
    data_tranformer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s2_data_transformer_pipeline.py", line 18, in main
    data_transformer.transform_data()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data\data_transformer.py", line 80, in transform_data
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\data\data_transformer.py", line 54, in transform_data
    df_train=pd.read_csv(self.config.data_train_path)
AttributeError: type object 'DataConfig' has no attribute 'data_train_path'
[2023-07-21 19:58:39,991: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 19:58:40,007: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 19:58:41,593: INFO: main: Data Ingestion stage started]
[2023-07-21 19:58:41,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:58:41,602: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 19:58:41,603: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 19:58:41,604: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 19:58:41,625: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 19:58:41,635: INFO: data_ingestion: Train and test data created.]
[2023-07-21 19:58:41,635: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 19:58:41,636: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 19:58:41,639: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:58:41,691: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 19:58:41,692: INFO: main: Model Training stage started]
[2023-07-21 19:58:41,693: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:15:31,244: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:15:31,244: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:16:01,825: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:16:01,826: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:16:03,393: INFO: main: Data Ingestion stage started]
[2023-07-21 20:16:03,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:16:03,401: ERROR: main: DataConfig.__init__() got an unexpected keyword argument 'data_transformed_X_train_array_path']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 17, in <module>
    data_ingestion_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 22, in main
    raise ex
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s1_data_ingestion_pipeline.py", line 19, in main
    data_ingestion = DataIngestion(config=config.get_data_config())
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 33, in get_data_config
    raise ex
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\configuration_manager.py", line 21, in get_data_config
    data_config = DataConfig(data_original_path=config.data_original_path,
TypeError: DataConfig.__init__() got an unexpected keyword argument 'data_transformed_X_train_array_path'
[2023-07-21 20:16:49,670: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:16:49,670: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:16:51,271: INFO: main: Data Ingestion stage started]
[2023-07-21 20:16:51,279: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:16:51,280: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:16:51,281: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:16:51,281: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:16:51,293: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:16:51,301: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:16:51,303: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:16:51,304: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:16:51,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:16:51,355: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:16:51,356: INFO: main: Model Training stage started]
[2023-07-21 20:16:51,356: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:17:28,537: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:17:28,539: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:17:31,044: INFO: main: Data Ingestion stage started]
[2023-07-21 20:17:31,059: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:17:31,059: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:17:31,059: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:17:31,059: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:17:31,076: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:17:31,086: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:17:31,087: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:17:31,087: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:17:31,092: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:17:31,163: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:17:31,164: INFO: main: Model Training stage started]
[2023-07-21 20:17:31,165: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:17:55,697: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:17:55,697: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:17:57,728: INFO: main: Data Ingestion stage started]
[2023-07-21 20:17:57,737: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:17:57,739: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:17:57,740: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:17:57,740: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:17:57,754: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:17:57,766: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:17:57,767: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:17:57,768: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:17:57,772: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:17:57,823: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:17:57,823: INFO: main: Model Training stage started]
[2023-07-21 20:17:57,839: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:19:18,032: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:19:18,032: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:19:20,649: INFO: main: Data Ingestion stage started]
[2023-07-21 20:19:20,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:19:20,666: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:19:20,667: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:19:20,668: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:19:20,685: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:19:20,697: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:19:20,699: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:19:20,700: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:19:20,706: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:19:20,763: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:19:20,763: INFO: main: Model Training stage started]
[2023-07-21 20:19:20,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:19:26,606: ERROR: main: [Errno 2] No such file or directory: 'config\\paramss.yaml']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 28, in read_yaml_dict
    raise e
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 21, in read_yaml_dict
    with open(path_to_yaml, encoding='utf8') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\paramss.yaml'
[2023-07-21 20:20:26,539: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:20:26,539: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:20:28,203: INFO: main: Data Ingestion stage started]
[2023-07-21 20:20:28,205: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:20:28,206: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:20:28,207: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:20:28,208: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:20:28,217: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:20:28,226: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:20:28,227: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:20:28,228: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:20:28,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:20:28,282: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:20:28,283: INFO: main: Model Training stage started]
[2023-07-21 20:20:28,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:20:28,286: INFO: common: yaml file: config\params.yaml loaded successfully]
[2023-07-21 20:20:28,287: ERROR: main: Return value of <function read_yaml_dict at 0x00000237CDF60EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x00000237CDF60EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:26:23,227: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:26:23,227: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:26:24,946: INFO: main: Data Ingestion stage started]
[2023-07-21 20:26:24,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:26:24,949: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:26:24,949: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:26:24,950: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:26:24,958: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:26:24,967: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:26:24,968: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:26:24,969: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:26:24,972: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:26:25,031: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:26:25,031: INFO: main: Model Training stage started]
[2023-07-21 20:26:25,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:26:25,034: INFO: common: No such file or directory]
[2023-07-21 20:26:25,034: ERROR: main: Return value of <function read_yaml_dict at 0x00000247E4990EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x00000247E4990EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:27:39,722: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:27:39,722: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:27:41,816: INFO: main: Data Ingestion stage started]
[2023-07-21 20:27:41,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:27:41,831: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:27:41,831: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:27:41,832: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:27:41,845: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:27:41,859: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:27:41,860: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:27:41,861: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:27:41,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:27:41,925: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:27:41,925: INFO: main: Model Training stage started]
[2023-07-21 20:27:41,938: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:28:35,017: INFO: common: No such file or directory]
[2023-07-21 20:28:49,308: ERROR: main: Return value of <function read_yaml_dict at 0x00000118A5360B80> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x00000118A5360B80> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:29:38,666: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:29:38,666: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:29:40,295: INFO: main: Data Ingestion stage started]
[2023-07-21 20:29:40,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:29:40,303: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:29:40,304: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:29:40,306: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:29:40,316: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:29:40,325: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:29:40,326: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:29:40,326: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:29:40,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:29:40,376: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:29:40,376: INFO: main: Model Training stage started]
[2023-07-21 20:29:40,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:29:40,398: ERROR: main: Return value of <function read_yaml_dict at 0x000001E5ED110EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x000001E5ED110EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:33:21,749: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:33:21,749: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:33:23,936: INFO: main: Data Ingestion stage started]
[2023-07-21 20:33:23,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:33:23,944: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:33:23,945: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:33:23,946: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:33:23,966: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:33:23,989: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:33:23,990: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:33:23,991: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:33:23,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:33:24,066: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:33:24,066: INFO: main: Model Training stage started]
[2023-07-21 20:33:24,075: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:34:26,785: ERROR: main: Return value of <function read_yaml_dict at 0x0000022805F60B80> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x0000022805F60B80> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:35:11,408: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:35:11,408: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:35:13,615: INFO: main: Data Ingestion stage started]
[2023-07-21 20:35:13,620: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:35:13,622: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:35:13,623: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:35:13,624: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:35:13,636: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:35:13,647: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:35:13,648: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:35:13,649: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:35:13,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:35:13,720: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:35:13,720: INFO: main: Model Training stage started]
[2023-07-21 20:35:13,728: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:37:10,811: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:37:10,811: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:37:12,497: INFO: main: Data Ingestion stage started]
[2023-07-21 20:37:12,504: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:37:12,505: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:37:12,507: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:37:12,509: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:37:12,518: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:37:12,527: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:37:12,528: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:37:12,530: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:37:12,532: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:37:12,585: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:37:12,586: INFO: main: Model Training stage started]
[2023-07-21 20:37:12,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:37:12,607: ERROR: main: Return value of <function read_yaml_dict at 0x000001AC13550EE0> of type <class 'type'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 7, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x000001AC13550EE0> of type <class 'type'> does not match annotation type <class 'dict'>
[2023-07-21 20:40:44,088: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:40:44,088: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:40:45,799: INFO: main: Data Ingestion stage started]
[2023-07-21 20:40:45,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:40:45,814: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:40:45,816: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:40:45,817: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:40:45,825: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:40:45,834: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:40:45,834: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:40:45,835: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:40:45,837: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:40:45,886: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:40:45,887: INFO: main: Model Training stage started]
[2023-07-21 20:40:45,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:40:45,910: ERROR: parameters_manager: Problem reading parameters yaml file: Return value of <function read_yaml_dict at 0x000001FC4CF50EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 11, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x000001FC4CF50EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:40:45,912: ERROR: main: 'ParametersManager' object has no attribute 'params']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 19, in __init__
    self.params = params_manager.get_params()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 17, in get_params
    return self.params
AttributeError: 'ParametersManager' object has no attribute 'params'
[2023-07-21 20:41:54,232: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:41:54,232: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:41:55,871: INFO: main: Data Ingestion stage started]
[2023-07-21 20:41:55,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:41:55,888: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:41:55,889: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:41:55,890: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:41:55,900: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:41:55,909: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:41:55,910: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:41:55,910: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:41:55,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:41:55,952: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:41:55,952: INFO: main: Model Training stage started]
[2023-07-21 20:41:55,964: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:41:55,985: ERROR: parameters_manager: Problem reading parameters yaml file: Return value of <function read_yaml_dict at 0x0000026DD4FC0EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 12, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x0000026DD4FC0EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:41:55,990: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:43:32,860: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:43:32,860: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:43:34,555: INFO: main: Data Ingestion stage started]
[2023-07-21 20:43:34,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:43:34,565: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:43:34,566: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:43:34,566: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:43:34,576: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:43:34,584: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:43:34,584: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:43:34,585: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:43:34,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:43:34,632: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:43:34,633: INFO: main: Model Training stage started]
[2023-07-21 20:43:34,635: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:43:34,636: INFO: common: yaml file loaded successfully: config\params.yaml ]
[2023-07-21 20:43:34,637: ERROR: parameters_manager: Problem reading parameters yaml file: Return value of <function read_yaml_dict at 0x000001CF65CE0EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 12, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml_dict at 0x000001CF65CE0EE0> of type <class 'NoneType'> does not match annotation type <class 'dict'>
[2023-07-21 20:43:34,639: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:44:23,169: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:44:23,170: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:44:25,436: INFO: main: Data Ingestion stage started]
[2023-07-21 20:44:25,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:44:25,442: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:44:25,443: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:44:25,445: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:44:25,461: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:44:25,474: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:44:25,475: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:44:25,476: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:44:25,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:44:25,555: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:44:25,556: INFO: main: Model Training stage started]
[2023-07-21 20:44:25,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:18,710: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:48:18,710: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:48:20,359: INFO: main: Data Ingestion stage started]
[2023-07-21 20:48:20,370: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:20,371: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:48:20,372: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:48:20,373: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:48:20,381: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:48:20,388: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:48:20,389: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:48:20,389: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:48:20,392: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:20,435: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:48:20,436: INFO: main: Model Training stage started]
[2023-07-21 20:48:20,438: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:20,439: INFO: common: yaml file is empty: config\params.yaml]
[2023-07-21 20:48:20,439: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:48:51,945: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:48:51,945: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:48:53,526: INFO: main: Data Ingestion stage started]
[2023-07-21 20:48:53,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:53,539: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:48:53,540: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:48:53,541: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:48:53,550: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:48:53,558: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:48:53,559: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:48:53,560: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:48:53,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:53,613: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:48:53,614: INFO: main: Model Training stage started]
[2023-07-21 20:48:53,616: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:48:53,618: ERROR: common: yaml file is empty: config\params.yaml]
NoneType: None
[2023-07-21 20:48:53,619: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:53:52,113: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:53:52,113: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:53:53,790: INFO: main: Data Ingestion stage started]
[2023-07-21 20:53:53,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:53:53,799: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:53:53,799: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:53:53,800: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:53:53,810: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:53:53,817: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:53:53,818: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:53:53,819: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:53:53,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:53:53,863: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:53:53,863: INFO: main: Model Training stage started]
[2023-07-21 20:53:53,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:53:53,866: INFO: common: ]
[2023-07-21 20:53:53,867: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:54:41,220: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:54:41,220: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:54:42,858: INFO: main: Data Ingestion stage started]
[2023-07-21 20:54:42,865: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:54:42,866: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:54:42,866: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:54:42,866: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:54:42,875: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:54:42,884: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:54:42,885: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:54:42,886: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:54:42,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:54:42,936: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:54:42,937: INFO: main: Model Training stage started]
[2023-07-21 20:54:42,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:54:42,940: ERROR: common: yaml file not found: config\params.yaml]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 22, in read_yaml_dict
    raise IOError
OSError
[2023-07-21 20:54:42,942: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:55:15,717: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:55:15,717: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:55:17,303: INFO: main: Data Ingestion stage started]
[2023-07-21 20:55:17,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:55:17,306: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:55:17,307: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:55:17,308: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:55:17,316: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:55:17,323: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:55:17,324: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:55:17,325: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:55:17,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:55:17,375: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:55:17,376: INFO: main: Model Training stage started]
[2023-07-21 20:55:17,378: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:55:17,379: ERROR: common: yaml file is empty: config\params.yaml]
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 22, in read_yaml_dict
    raise IOError
OSError
[2023-07-21 20:55:17,381: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 20:55:32,084: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 20:55:32,084: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 20:55:33,897: INFO: main: Data Ingestion stage started]
[2023-07-21 20:55:33,899: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:55:33,899: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 20:55:33,900: INFO: common: removed file at: artifacts/data/original_data/train_data.csv]
[2023-07-21 20:55:33,901: INFO: common: removed file at: artifacts/data/original_data/test_data.csv]
[2023-07-21 20:55:33,909: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 20:55:33,916: INFO: data_ingestion: Train and test data created.]
[2023-07-21 20:55:33,917: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 20:55:33,918: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 20:55:33,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:55:33,964: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 20:55:33,965: INFO: main: Model Training stage started]
[2023-07-21 20:55:33,967: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 20:55:33,967: ERROR: common: [Errno 2] No such file or directory: 'config\\paramss.yaml']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 19, in read_yaml_dict
    with open(path_to_yaml, encoding='utf8') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\paramss.yaml'
[2023-07-21 20:55:33,969: INFO: main: Model Training stage completed
x==========x]
[2023-07-21 21:11:12,709: INFO: utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-07-21 21:11:12,709: INFO: utils: NumExpr defaulting to 8 threads.]
[2023-07-21 21:11:14,508: INFO: main: Data Ingestion stage started]
[2023-07-21 21:11:14,520: INFO: common: yaml file loaded successfully: config\config.yaml]
[2023-07-21 21:11:14,522: INFO: data_ingestion: Data already exists. Deleting existing data.]
[2023-07-21 21:11:14,524: INFO: common: removed file at artifacts/data/original_data/train_data.csv:]
[2023-07-21 21:11:14,525: INFO: common: removed file at artifacts/data/original_data/test_data.csv:]
[2023-07-21 21:11:14,540: INFO: data_ingestion: Input data file loaded.]
[2023-07-21 21:11:14,548: INFO: data_ingestion: Train and test data created.]
[2023-07-21 21:11:14,549: INFO: main: Data Ingestion stage completed
x==========x]
[2023-07-21 21:11:14,549: INFO: main: Data Transformation stage started <<<<<<]
[2023-07-21 21:11:14,552: INFO: common: yaml file loaded successfully: config\config.yaml]
[2023-07-21 21:11:14,596: INFO: main: Data Transformation stage completed
x==========x]
[2023-07-21 21:11:14,597: INFO: main: Model Training stage started]
[2023-07-21 21:11:14,599: INFO: common: yaml file loaded successfully: config\config.yaml]
[2023-07-21 21:11:14,600: ERROR: common: [Errno 2] No such file or directory: 'config\\paramss.yaml']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 18, in read_yaml_dict
    with open(path_to_yaml, encoding='utf8') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\paramss.yaml'
[2023-07-21 21:11:14,602: ERROR: main: [Errno 2] No such file or directory: 'config\\paramss.yaml']
Traceback (most recent call last):
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\main.py", line 39, in <module>
    model_trainer_pipe.main()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\pipeline\training_pipeline\s3_model_trainer_pipeline.py", line 12, in main
    model_builder_trainer = ModelBuilder(
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\components\model\model_builder.py", line 18, in __init__
    params_manager = ParametersManager()
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\configuration\parameters_manager.py", line 12, in __init__
    self.params=read_yaml_dict(params_file_path)
  File "C:\Users\fhash\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 26, in read_yaml_dict
    raise exc
  File "C:\Data\Study\AI\AI_Projects\ML_Generic\src\utils\common.py", line 18, in read_yaml_dict
    with open(path_to_yaml, encoding='utf8') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\paramss.yaml'
